export const FETCH_ARTISTS_SUCCESS = "FETCH_ARTISTS_SUCCESS";
export const FETCH_ARTISTS_ERROR = "FETCH_ARTISTS_ERROR";

export const FETCH_ARTIST_SUCCESS = "FETCH_ARTIST_SUCCESS";
export const FETCH_ARTIST_ERROR = "FETCH_ARTIST_ERROR";

export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const FETCH_TRACKS_ERROR = "FETCH_TRACKS_ERROR";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const ADD_TRACK_FAILURE = "ADD_TRACK_FAILURE";

export const FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS";
export const FETCH_HISTORY_ERROR = "FETCH_HISTORY_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_ARTIST_ERROR = "ADD_ARTIST_ERROR"
export const ADD_ALBUM_ERROR = "ADD_ALBUM_ERROR"
export const ADD_TRACK_ERROR = "ADD_TRACK_ERROR"

export const DELETE_ARTIST_ERROR = "DELETE_ARTIST_ERROR";
export const DELETE_ALBUM_ERROR = "DELETE_ALBUM_ERROR";
export const DELETE_TRACK_ERROR = "DELETE_TRACK_ERROR";

export const PUBLIC_ARTIST_ERROR = "PUBLIC_ARTIST_ERROR";
export const PUBLIC_ALBUM_ERROR = "PUBLIC_ALBUM_ERROR";
export const PUBLIC_TRACK_ERROR = "PUBLIC_TRACK_ERROR";